// Configuration for dream.uniflo.ai microservices
module.exports = {
    apps: [
        {
            name: 'dream-gateway-service',
            script: './gateway-service/src/index.js',
            cwd: '/home/ubuntu/projects/dream/Backend',
            watch: true,
            env: {
                NODE_ENV: 'development',
                PORT: 4020, // Gateway port for dream.uniflo.ai
                SERVICE_TOKEN: 'Dream_notify_secret',
                JWT_SECRET: 'Dream_jwt_secret',
                // Explicitly set microservice URLs to avoid using default ports (4001-4006)
                AUTH_SERVICE_URL: 'http://localhost:4021',
                TEMPLATES_SERVICE_URL: 'http://localhost:4024',
                SETTINGS_SERVICE_URL: 'http://localhost:4023',
                DISPUTES_SERVICE_URL: 'http://localhost:4022',
                EXTERNAL_API_SERVICE_URL: 'http://localhost:4025',
                USERS_SERVICE_URL: 'http://localhost:4021' // Assuming auth handles users
            },
            env_production: {
                NODE_ENV: 'production',
                PORT: 4020,
                SERVICE_TOKEN: 'Dream_notify_secret',
                JWT_SECRET: 'Dream_jwt_secret',
                AUTH_SERVICE_URL: 'http://localhost:4021',
                TEMPLATES_SERVICE_URL: 'http://localhost:4024',
                SETTINGS_SERVICE_URL: 'http://localhost:4023',
                DISPUTES_SERVICE_URL: 'http://localhost:4022',
                EXTERNAL_API_SERVICE_URL: 'http://localhost:4025',
                USERS_SERVICE_URL: 'http://localhost:4021'
            },
        },
        {
            name: 'dream-auth-service',
            script: './auth-service/src/index.js',
            cwd: '/home/ubuntu/projects/dream/Backend',
            watch: true,
            env: {
                NODE_ENV: 'development',
                PORT: 4021,
                DB_HOST: 'localhost',
                DB_USER: 'postgres',
                DB_PASS: 'anilVyvaMca',
                DB_NAME: 'dream',
                DB_PORT: '5432',
                JWT_SECRET: 'Dream_jwt_secret',
                REFRESH_SECRET: 'Dream_refresh_secret',
            },
            env_production: {
                NODE_ENV: 'production',
                PORT: 4021,
                DB_HOST: 'localhost',
                DB_USER: 'postgres',
                DB_PASS: 'anilVyvaMca',
                DB_NAME: 'dream',
                DB_PORT: '5432',
                JWT_SECRET: 'Dream_jwt_secret',
                REFRESH_SECRET: 'Dream_refresh_secret',
            },
        },
        {
            name: 'dream-dispute-service',
            script: './dispute-service/src/index.js',
            cwd: '/home/ubuntu/projects/dream/Backend',
            watch: true,
            env: {
                NODE_ENV: 'development',
                PORT: 4022,
                DB_HOST: 'localhost',
                DB_USER: 'postgres',
                DB_PASS: 'anilVyvaMca',
                DB_NAME: 'dream',
                DB_PORT: '5432',
                JWT_SECRET: 'Dream_jwt_secret',
                REFRESH_SECRET: 'Dream_refresh_secret',
            },
            env_production: {
                NODE_ENV: 'production',
                PORT: 4022,
                DB_HOST: 'localhost',
                DB_USER: 'postgres',
                DB_PASS: 'anilVyvaMca',
                DB_NAME: 'dream',
                DB_PORT: '5432',
                JWT_SECRET: 'Dream_jwt_secret',
                REFRESH_SECRET: 'Dream_refresh_secret',
            },
        },
        {
            name: 'dream-settings-service',
            script: './settings-service/src/index.js',
            cwd: '/home/ubuntu/projects/dream/Backend',
            watch: true,
            env: {
                NODE_ENV: 'development',
                PORT: 4023,
                DB_HOST: 'localhost',
                DB_USER: 'postgres',
                DB_PASS: 'anilVyvaMca',
                DB_NAME: 'dream',
                DB_PORT: '5432',
                JWT_SECRET: 'Dream_jwt_secret',
                REFRESH_SECRET: 'Dream_refresh_secret',
            },
            env_production: {
                NODE_ENV: 'production',
                PORT: 4023,
                DB_HOST: 'localhost',
                DB_USER: 'postgres',
                DB_PASS: 'anilVyvaMca',
                DB_NAME: 'dream',
                DB_PORT: '5432',
                JWT_SECRET: 'Dream_jwt_secret',
                REFRESH_SECRET: 'Dream_refresh_secret',
            },
        },
        {
            name: 'dream-template-service',
            script: './template-service/src/index.js',
            cwd: '/home/ubuntu/projects/dream/Backend',
            watch: true,
            env: {
                NODE_ENV: 'development',
                PORT: 4024,
                DB_HOST: 'localhost',
                DB_USER: 'postgres',
                DB_PASS: 'anilVyvaMca',
                DB_NAME: 'dream',
                DB_PORT: '5432',
                JWT_SECRET: 'Dream_jwt_secret',
                REFRESH_SECRET: 'Dream_refresh_secret',
            },
            env_production: {
                NODE_ENV: 'production',
                PORT: 4024,
                DB_HOST: 'localhost',
                DB_USER: 'postgres',
                DB_PASS: 'anilVyvaMca',
                DB_NAME: 'dream',
                DB_PORT: '5432',
                JWT_SECRET: 'Dream_jwt_secret',
                REFRESH_SECRET: 'Dream_refresh_secret',
            },
        },
        {
            name: 'dream-external-api-services',
            script: './external-api-services/src/index.js',
            cwd: '/home/ubuntu/projects/dream/Backend',
            watch: true,
            env: {
                NODE_ENV: 'development',
                PORT: 4025,
                DB_HOST: 'localhost',
                DB_USER: 'postgres',
                DB_PASS: 'anilVyvaMca',
                DB_NAME: 'dream',
                DB_PORT: '5432',
                JWT_SECRET: 'Dream_jwt_secret',
                REFRESH_SECRET: 'Dream_refresh_secret',
            },
            env_production: {
                NODE_ENV: 'production',
                PORT: 4025,
                DB_HOST: 'localhost',
                DB_USER: 'postgres',
                DB_PASS: 'anilVyvaMca',
                DB_NAME: 'dream',
                DB_PORT: '5432',
                JWT_SECRET: 'Dream_jwt_secret',
                REFRESH_SECRET: 'Dream_refresh_secret',
            },
        },
    ],
};