const getAddUserSchema = {
  feilds: [
    {
      id: 1,
      name: 'first_name',
      label: 'First Name',
      element: 'input',
      value: '',
      required: true,
      disable: false,
      visable: true,
    },
    {
      id: 2,
      name: 'last_name',
      label: 'Last Name',
      element: 'input',
      value: '',
      required: true,
      disable: false,
      visable: true,
    },
    {
      id: 3,
      name: 'emp_id',
      label: 'Employee ID',
      element: 'input',
      value: '',
      required: true,
      disable: false,
      visable: true,
    },
    {
      id: 4,
      name: 'email',
      label: 'Email',
      element: 'input',
      type: 'email',
      value: '',
      required: true,
      disable: false,
      visable: true,
    },
    {
      id: 6,
      name: 'roles',
      fkey: 'role_id',
      label: 'Role',
      element: 'Select',
      placeholder: 'Select Role',
      value: '',
      required: true,
      disable: false,
      visable: true,
    },
    {
      id: 9,
      name: 'reporting_to',
      label: 'Reporting User',
      element: 'Select',
      placeholder: 'Select Reporting User',
      value: '',
      required: false,
      disable: false,
      visable: true,
    },
    {
      id: 10,
      name: 'region',
      label: 'Region',
      element: 'Select', // Changed from 'input' to 'Select'
      placeholder: 'Select Region',
      value: '',
      required: false,
      disable: false,
      visable: true,
    },
    {
      id: 11,
      name: 'sub_region',
      label: 'Sub-region',
      element: 'Select',
      placeholder: 'Select Sub-region',
      value: '',
      required: false,
      disable: false,
      visable: true,
    },
    {
      id: 12,
      name: 'department',
      label: 'Department',
      element: 'input',
      value: '',
      required: false,
      disable: false,
      visable: true,
    },
    {
      id: 13,
      name: 'license_type',
      label: 'License Type',
      element: 'Select',
      placeholder: 'Select License Type',
      value: '',
      required: false,
      disable: false,
      visable: true,
    },
    {
      id: 14,
      name: 'user_active',
      label: 'Active User',
      element: 'switch',
      placeholder: 'switch',
      value: false, // Default to false for switch
      required: false,
      disable: false,
      visable: true,
    },
  ],
};

export { getAddUserSchema };