version: '3.8'

services:
  postgres:
    image: postgres:13
    environment:
      DB_USER: postgres
      DB_PASS: root
      DB_NAME: disputeDB
    ports:
      - '5432:5432'

  auth-service:
    build: ./auth-service
    environment:
      JWT_SECRET: secret
      REFRESH_SECRET: refresh_secret
    ports:
      - '4000:4000'
    depends_on:
      - postgres
