name: Dream CI/CD – Backend

on:
  push:
    branches: [ main ]
    paths: [ 'Backend/**', '.github/workflows/dreamcicd-backend.yml' ]
  workflow_dispatch: {}   # manual run / rollback

concurrency:
  group: dream-backend
  cancel-in-progress: true

jobs:
  cd:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          ref: ${{ github.event.inputs.ref || github.ref }}

      - name: Rsync Backend -> server
        uses: burnett01/rsync-deployments@6.0.0
        with:
          switches: -avzr --delete --exclude="node_modules" --exclude=".env" --exclude=".env.*" --exclude="*.log"
          path: Backend/
          remote_path: /home/ubuntu/projects/dream/Backend/
          remote_host: ${{ secrets.SERVER_HOST }}
          remote_user: ${{ secrets.SERVER_USER }}
          remote_key: ${{ secrets.SERVER_SSH_KEY }}

      - name: Install deps & PM2 reload (dream apps only)
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SERVER_SSH_KEY }}
          script: |
            set -e
            cd /home/ubuntu/projects/dream/Backend
            for svc in gateway-service auth-service dispute-service settings-service template-service external-api-services; do
              [ -f "./$svc/package.json" ] || continue
              (cd "$svc" && (npm ci --omit=dev || npm install --omit=dev))
            done
            pm2 startOrReload /home/ubuntu/projects/dream/Backend/dream-ecosystem.config.js --env production
            pm2 save
            # Build info for traceability
            cat > /home/ubuntu/projects/dream/Backend/BUILD_INFO.json <<'JSON'
            { "app":"dream-backend","sha":"${{ github.sha }}","run_id":"${{ github.run_id }}","actor":"${{ github.actor }}","timestamp":"${{ github.run_started_at }}" }
            JSON
