name: Dream CI/CD – Frontend

on:
  push:
    branches: [ main ]
    paths: [ 'Frontend/**', '.github/workflows/dreamcicd-frontend.yml' ]
  workflow_dispatch: {}   # manual run / rollback

concurrency:
  group: dream-frontend
  cancel-in-progress: true

jobs:
  ci-cd:
    runs-on: ubuntu-latest
    defaults: { run: { working-directory: Frontend } }
    steps:
      - uses: actions/checkout@v4
        with:
          ref: ${{ github.event.inputs.ref || github.ref }}

      - uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: npm
          cache-dependency-path: Frontend/package-lock.json

      - run: npm ci || npm install
      - env: { NODE_ENV: production }
        run: npm run build

      - name: Add build info file
        run: |
          echo "{\"app\":\"dream-frontend\",\"sha\":\"$GITHUB_SHA\",\"run_id\":\"$GITHUB_RUN_ID\",\"timestamp\":\"$(date -u +%FT%TZ)\"}" > Frontend/dist/build-info.json

      - name: Rsync dist -> server
        uses: burnett01/rsync-deployments@6.0.0
        with:
          switches: -avzr --delete --exclude="*.map"
          path: Frontend/dist/
          remote_path: /home/ubuntu/projects/dream/Frontend/dist/   # <-- Capital F (important)
          remote_host: ${{ secrets.SERVER_HOST }}
          remote_user: ${{ secrets.SERVER_USER }}
          remote_key: ${{ secrets.SERVER_SSH_KEY }}

      - name: Reload Nginx
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SERVER_SSH_KEY }}
          script: sudo nginx -t && sudo systemctl reload nginx
